# Generated by Django 3.0.4 on 2020-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_pollmodel_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollmodel',
            old_name='price',
            new_name='time_to_poll',
        ),
    ]
