# Generated by Django 3.0.4 on 2020-05-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200513_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('frequence_in_secs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_ts', models.DateTimeField(auto_now_add=True)),
                ('secs_for_first_response', models.IntegerField()),
                ('response_code', models.IntegerField()),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Monitor')),
            ],
        ),
        migrations.DeleteModel(
            name='pollmodel',
        ),
    ]
